# Generated by Django 3.1.2 on 2020-11-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=30)),
                ('email', models.CharField(help_text='Email address for email notification', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(max_length=1024)),
                ('server', models.ManyToManyField(help_text='Serving member for day', to='scheduler.Member')),
            ],
        ),
    ]
