# Generated by Django 3.1.2 on 2020-11-02 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servingday',
            name='server',
        ),
        migrations.AddField(
            model_name='servingday',
            name='server',
            field=models.ForeignKey(help_text='Serving member for day', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.member'),
        ),
    ]
